version: "3.7"
services:
    app:
        image: "lnlscon/utility:v1.9"
        build: "."
        volumes:
            - ".:/opt/cons-utility-api"
            - "./extra/Redes e Beaglebones.xlsx:/opt/Redes e Beaglebones.xlsx:ro"
        ports:
            - 8080:80
        networks:
            - auth-proxy
        env_file:
            - ./env_file

    redis:
        image: "redis:6-alpine"
        hostname: "redis"
        networks:
            - auth-proxy

networks:
    auth-proxy:
