version: "3.7"
services:
    app:
        image: "lnlscon/utility:v1.4"
        build: "."
        volumes:
            - "/home/carneirofc/Devel/cons-utility-api/Redes e Beaglebones.xlsx:/opt/spreadsheet/Redes e Beaglebones.xlsx:ro"
        ports:
            - 8080:80
